version: '3'

services:
  api:
    image: ${DEV_CONTAINER_IMAGE_ID}
    container_name: ${DEV_CONTAINER_NAME}
    build:
      args:
        ARG_NODE_ENV : ${DEV_NODE_ENV}
        ARG_PORT_EXPOSE: ${DEV_PORT_EXPOSE}
        ARG_PORT_CONTAINER: ${DEV_PORT_CONTAINER}
        ARG_PORT_HOST: ${DEV_PORT_HOST}
        ARG_PORT_DEBUG_CONTAINER: ${DEV_PORT_DEBUG_CONTAINER}
        ARG_PORT_DEBUG_HOST: ${DEV_PORT_DEBUG_HOST}
        ARG_WORKING_DIR: ${DEV_WORKING_DIR}
        ARG_CONTAINER_NAME: ${DEV_CONTAINER_NAME}
        ARG_CONTAINER_IMAGE_ID: ${DEV_CONTAINER_IMAGE_ID}
        ARG_VOLUME_HOST: ${DEV_VOLUME_HOST}
        ARG_VOLUME_CONTAINER: ${DEV_VOLUME_CONTAINER}
        ARG_SENTRY: ${DEV_SENTRY}
        ARG_TOKEN_AUDIENCE: ${DEV_TOKEN_AUDIENCE}
        ARG_TOKEN_SUBJECT: ${DEV_TOKEN_SUBJECT}
        ARG_TOKEN_ISSUER: ${DEV_TOKEN_ISSUER}
        ARG_TOKEN_TTL: ${DEV_TOKEN_TTL}
        ARG_TOKEN_SECRET: ${DEV_TOKEN_SECRET}

      context: ./

    volumes:
      - ${DEV_VOLUME_HOST}:${DEV_VOLUME_CONTAINER}
    expose:
      - ${DEV_PORT_EXPOSE}
    ports:
      - "${DEV_HOST}:${DEV_PORT_CONTAINER}:${DEV_PORT_HOST}"
      - "${DEV_HOST}:${DEV_PORT_DEBUG_CONTAINER}:${DEV_PORT_DEBUG_HOST}"
    working_dir: ${DEV_WORKING_DIR}
    entrypoint: npm run dev

