version: '3'

services:
  api:
    image: ${BETA_CONTAINER_IMAGE_ID}
    container_name: ${BETA_CONTAINER_NAME}
    build:
      args:
        ARG_NODE_ENV : ${BETA_NODE_ENV}
        ARG_PORT_EXPOSE: ${BETA_PORT_EXPOSE}
        ARG_PORT_CONTAINER: ${BETA_PORT_CONTAINER}
        ARG_PORT_HOST: ${BETA_PORT_HOST}
        ARG_PORT_DEBUG_CONTAINER: ${BETA_PORT_DEBUG_CONTAINER}
        ARG_PORT_DEBUG_HOST: ${BETA_PORT_DEBUG_HOST}
        ARG_WORKING_DIR: ${BETA_WORKING_DIR}
        ARG_CONTAINER_NAME: ${BETA_CONTAINER_NAME}
        ARG_CONTAINER_IMAGE_ID: ${BETA_CONTAINER_IMAGE_ID}
        ARG_VOLUME_HOST: ${BETA_VOLUME_HOST}
        ARG_VOLUME_CONTAINER: ${BETA_VOLUME_CONTAINER}
        ARG_SENTRY: ${BETA_SENTRY}
        ARG_TOKEN_AUDIENCE: ${BETA_TOKEN_AUDIENCE}
        ARG_TOKEN_SUBJECT: ${BETA_TOKEN_SUBJECT}
        ARG_TOKEN_ISSUER: ${BETA_TOKEN_ISSUER}
        ARG_TOKEN_TTL: ${BETA_TOKEN_TTL}
        ARG_TOKEN_SECRET: ${BETA_TOKEN_SECRET}
      context: ./

    volumes:
      - ${BETA_VOLUME_HOST}:${BETA_VOLUME_CONTAINER}
    expose:
      - ${BETA_PORT_EXPOSE}
    ports:
      - "${BETA_HOST}:${BETA_PORT_CONTAINER}:${BETA_PORT_HOST}"
      - "${BETA_HOST}:${BETA_PORT_DEBUG_CONTAINER}:${BETA_PORT_DEBUG_HOST}"
    working_dir: ${BETA_WORKING_DIR}
    entrypoint: npm run beta

